version: "3.9"  # optional since v1.27.0
services:
  frontend:
    build: 
      context: .
      dockerfile: ./Frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: 
      context: .
      dockerfile: ./Backend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=dev
      - MONGO_DB_CONNECTION_STRING=example
      - MONGO_DB_NAME=CloudProjectDB
      - REDIS_URI=redis://redis:6379
  
  redis:
    image: redis
    ports:
      - "6379:6379"
      